---
id: yarp
tags:
- rabbit
- theme
- yarp
version: 1.0.0
licenses:
- CC-BY-SA-3.0
author:
  markup_language: :markdown
  name: Daniele E. Domenichelli
  email: daniele.domenichelli@iit.it
  rubygems_user: drdanz
  slideshare_user: 
  speaker_deck_user: 
